language: node_js

node_js:
  - 8

script:
  - npm install
  - npm run build

notifications:
  email:
    - rlreamy@umich.edu
    - zwright@umich.edu
    - royerbr@med.umich.edu
    - cgates@umich.edu
    - cspital@uw.edu
