language: node_js

script:
  - node ./internals/scripts/generate-templates-for-linting
  - npm test -- --maxWorkers=4
  - npm run build

notifications:
  email:
    - rlreamy@umich.edu
    - zwright@umich.edu
    - royerbr@med.umich.edu
